/**
 * TrackYu Mobile — Reports: 10 modules + sous-rapports
 */
import {
  Truck,
  Zap,
  Fuel,
  Users,
  CreditCard,
  BookOpen,
  Wrench,
  LifeBuoy,
  Settings,
  Shield,
  BarChart2,
  Route,
  Clock,
  WifiOff,
  TrendingUp,
  MapPin,
  AlertTriangle,
  FileText,
  Check,
  Mail,
  Package,
  UserCheck,
  Calculator,
  Database,
  Lock,
  Receipt,
  Thermometer,
  Gauge,
  CircleDot,
  Leaf,
  Navigation,
} from 'lucide-react-native';
import { ReportModule, ALL_ROLES, ADMIN_ROLES, FINANCE_ROLES } from './types';
import { ROLE } from '../../../constants/roles';

const CRM_ROLES = [ROLE.COMMERCIAL, ROLE.ADMIN, ROLE.SUPERADMIN];
const TECH_ROLES = [ROLE.TECH, ROLE.ADMIN, ROLE.SUPERADMIN];
const SUPPORT_ROLES = [ROLE.TECH, ROLE.COMMERCIAL, ROLE.ADMIN, ROLE.SUPERADMIN];
const CLIENT_ROLES = ALL_ROLES;

export const REPORT_MODULES: ReportModule[] = [
  // ── 1. ACTIVITÉS ───────────────────────────────────────────────────────────
  {
    id: 'activity',
    title: 'Activités',
    subtitle: 'Activité des engins, trajets et kilométrage',
    IconComponent: Truck,
    color: '#3B82F6',
    roles: CLIENT_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs flotte : statuts, distance, alertes, ralentis',
        filterKeys: ['vehicle', 'client'],
        IconComponent: BarChart2,
      },
      {
        id: 'general',
        title: 'Activité générale',
        description: 'Snapshot de tous les engins — statut, vitesse, odomètre',
        filterKeys: ['vehicle', 'client', 'branche', 'revendeur'],
        IconComponent: Truck,
      },
      {
        id: 'trajets',
        title: 'Trajets détaillés',
        description: 'Liste des trajets — départ, arrivée, durée, distance',
        filterKeys: ['vehicle', 'client'],
        IconComponent: Route,
      },
      {
        id: 'kilometrage',
        title: 'Kilométrage',
        description: 'Distance parcourue par engin sur la période',
        filterKeys: ['vehicle', 'client'],
        IconComponent: TrendingUp,
      },
      {
        id: 'daily',
        title: 'Distance quotidienne',
        description: 'Pivot : engins en lignes, jours du mois en colonnes',
        filterKeys: ['vehicle', 'client'],
        IconComponent: BarChart2,
      },
      {
        id: 'idle',
        title: 'Ralentis (IDLE)',
        description: 'Engins moteur allumé sans mouvement',
        filterKeys: ['vehicle', 'client'],
        IconComponent: Clock,
      },
      {
        id: 'stopped',
        title: 'Arrêts (STOPPED)',
        description: "Engins à l'arrêt sur la période",
        filterKeys: ['vehicle', 'client'],
        IconComponent: Clock,
      },
      {
        id: 'offline',
        title: 'Hors ligne (OFFLINE)',
        description: 'Engins sans signal GPS',
        filterKeys: ['vehicle', 'client', 'revendeur'],
        IconComponent: WifiOff,
      },
    ],
  },

  // ── 2. ALERTES ─────────────────────────────────────────────────────────────
  {
    id: 'alerts',
    title: 'Alertes',
    subtitle: 'Infractions, événements et statut des notifications',
    IconComponent: Zap,
    color: '#EF4444',
    roles: CLIENT_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs alertes : types, sévérités, non lues, tendance',
        filterKeys: ['vehicle', 'client'],
        IconComponent: BarChart2,
      },
      {
        id: 'all',
        title: 'Toutes les alertes',
        description: 'Historique complet avec filtres type/sévérité',
        filterKeys: ['vehicle', 'client', 'branche', 'revendeur', 'alertType'],
        IconComponent: AlertTriangle,
      },
      {
        id: 'geofence',
        title: 'Alertes géofence',
        description: 'Franchissements et violations de zones géographiques',
        filterKeys: ['vehicle', 'client'],
        IconComponent: MapPin,
      },
      {
        id: 'notifications',
        title: 'Statut Email/SMS',
        description: 'Emails et SMS envoyés — statut de livraison',
        filterKeys: ['vehicle', 'client', 'revendeur'],
        IconComponent: Mail,
      },
    ],
  },

  // ── 3. CARBURANT ───────────────────────────────────────────────────────────
  {
    id: 'fuel',
    title: 'Carburant',
    subtitle: 'Niveaux, recharges, consommation et anomalies',
    IconComponent: Fuel,
    color: '#F59E0B',
    roles: CLIENT_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs carburant : niveaux moyens, alertes, recharges',
        filterKeys: ['vehicle', 'client'],
        IconComponent: BarChart2,
      },
      {
        id: 'levels',
        title: 'Niveaux actuels',
        description: 'État carburant de tous les engins',
        filterKeys: ['vehicle', 'client', 'branche'],
        IconComponent: Fuel,
      },
      {
        id: 'critical',
        title: 'Critique & Bas (< 40%)',
        description: 'Engins nécessitant un ravitaillement',
        filterKeys: ['vehicle', 'client'],
        IconComponent: AlertTriangle,
      },
      {
        id: 'refills',
        title: 'Recharges',
        description: 'Historique des ravitaillements détectés',
        filterKeys: ['vehicle', 'client'],
        IconComponent: TrendingUp,
      },
      {
        id: 'drops',
        title: 'Baisses de carburant',
        description: 'Baisses significatives détectées sur la période',
        filterKeys: ['vehicle', 'client'],
        IconComponent: TrendingUp,
      },
      {
        id: 'consumption',
        title: 'Consommation (capteurs)',
        description: 'Données de consommation issues des capteurs',
        filterKeys: ['vehicle', 'client'],
        IconComponent: BarChart2,
      },
      {
        id: 'vs_theo',
        title: 'Réelle vs Théorique',
        description: 'Comparaison consommation réelle et consommation théorique',
        filterKeys: ['vehicle', 'client'],
        IconComponent: BarChart2,
      },
      {
        id: 'anomalies',
        title: 'Anomalies',
        description: 'Données anormales : pics, chutes, incohérences',
        filterKeys: ['vehicle', 'client'],
        IconComponent: AlertTriangle,
      },
    ],
  },

  // ── 4. CRM ─────────────────────────────────────────────────────────────────
  {
    id: 'crm',
    title: 'CRM',
    subtitle: 'Pipeline commercial, devis, ventes et performance',
    IconComponent: Users,
    color: '#8B5CF6',
    roles: CRM_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs CRM : pipeline, conversion, valeur générée',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BarChart2,
      },
      {
        id: 'leads',
        title: 'Leads',
        description: 'Pipeline complet — filtre par statut (gagné/perdu/en cours)',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Users,
      },
      {
        id: 'performance',
        title: 'Performance commerciale',
        description: 'Taux de conversion et valeur par commercial',
        filterKeys: ['revendeur'],
        IconComponent: TrendingUp,
      },
      {
        id: 'quotes',
        title: 'Devis',
        description: 'Devis émis — statut, montant, conversion en facture',
        filterKeys: ['client', 'revendeur'],
        IconComponent: FileText,
      },
      {
        id: 'ventes',
        title: 'Ventes',
        description: 'Ventes par client et par article sur la période',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Package,
      },
      {
        id: 'sales_summary',
        title: 'Résumé des ventes',
        description: 'Synthèse journalière : nb factures et montant TTC par jour',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BarChart2,
      },
    ],
  },

  // ── 5. FINANCE ─────────────────────────────────────────────────────────────
  {
    id: 'finance',
    title: 'Finance',
    subtitle: 'Gestion des flux : factures, encaissements, dépenses et contrats',
    IconComponent: CreditCard,
    color: '#06B6D4',
    roles: FINANCE_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Tableau de bord',
        description: 'MRR, CA facturé, encaissé, impayé, taux recouvrement',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BarChart2,
      },
      {
        id: 'invoices',
        title: 'Factures',
        description: 'Toutes les factures filtrées par statut, client et période',
        filterKeys: ['client', 'branche', 'revendeur'],
        IconComponent: FileText,
      },
      {
        id: 'overdue',
        title: 'Impayées & Recouvrement',
        description: 'Factures non réglées — niveaux de relance et montants dus',
        filterKeys: ['client', 'revendeur'],
        IconComponent: AlertTriangle,
      },
      {
        id: 'payments',
        title: 'Encaissements',
        description: 'Historique des paiements reçus par méthode et client',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Check,
      },
      {
        id: 'depenses',
        title: 'Dépenses véhicules',
        description: 'Carburant, péage, réparation, assurance et autres charges',
        filterKeys: [],
        IconComponent: Receipt,
      },
      {
        id: 'bilan',
        title: 'Bilan mensuel',
        description: 'Facturé · Encaissé · Dépenses · Solde net — 12 mois glissants',
        filterKeys: ['client', 'revendeur'],
        IconComponent: TrendingUp,
      },
      {
        id: 'contracts',
        title: 'Contrats',
        description: 'Contrats actifs, suspendus et résiliés — MRR et ARR',
        filterKeys: ['client', 'revendeur'],
        IconComponent: FileText,
      },
      {
        id: 'renewals',
        title: 'Renouvellements',
        description: 'Contrats expirant dans 30 · 60 · 90 jours — tri par urgence',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Clock,
      },
    ],
  },

  // ── 6. COMPTABILITÉ ────────────────────────────────────────────────────────
  {
    id: 'accounting',
    title: 'Comptabilité',
    subtitle: 'Journaux comptables, balance âgée, TVA et export FEC',
    IconComponent: BookOpen,
    color: '#10B981',
    roles: FINANCE_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse comptable',
        description: 'CA HT, TVA collectée, créances, encaissements et taux de recouvrement',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BarChart2,
      },
      {
        id: 'sales_journal',
        title: 'Journal des ventes',
        description: 'Écritures de vente avec comptes 411 / 706 / 44571',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BookOpen,
      },
      {
        id: 'receipts_journal',
        title: 'Journal des encaissements',
        description: 'Écritures de règlement avec comptes 512 / 411 par méthode',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BookOpen,
      },
      {
        id: 'aged_balance',
        title: 'Balance âgée clients',
        description: 'Créances impayées par ancienneté : non échu · 1-30j · 31-60j · +90j',
        filterKeys: ['client', 'revendeur'],
        IconComponent: AlertTriangle,
      },
      {
        id: 'reconciliation',
        title: 'Rapprochement bancaire',
        description: 'Facturé vs encaissé — détection des écarts et paiements non rapprochés',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Check,
      },
      {
        id: 'vat_state',
        title: 'État TVA',
        description: 'TVA collectée et exigible par taux — prête pour déclaration fiscale',
        filterKeys: ['revendeur'],
        IconComponent: Calculator,
      },
      {
        id: 'fec_export',
        title: 'Export FEC',
        description: 'Fichier des Écritures Comptables au format normalisé DGFiP',
        filterKeys: ['revendeur'],
        IconComponent: Database,
      },
    ],
  },

  // ── 7. TECHNIQUE ───────────────────────────────────────────────────────────
  {
    id: 'technique',
    title: 'Technique',
    subtitle: 'Interventions, maintenance, flotte et monitoring',
    IconComponent: Wrench,
    color: '#22C55E',
    roles: TECH_ROLES,
    // Le rôle TECH ne voit que ces 5 sous-rapports (limités à ses propres interventions)
    techSubReportIds: ['all', 'by_nature', 'by_tech', 'timing', 'planning'],
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs : interventions, délais, coûts, stock critique',
        filterKeys: ['client', 'revendeur'],
        IconComponent: BarChart2,
      },
      // ── Interventions ──
      {
        id: 'all',
        title: 'Toutes les interventions',
        description: 'Historique complet des interventions',
        filterKeys: ['vehicle', 'client', 'branche', 'revendeur'],
        IconComponent: Wrench,
      },
      {
        id: 'by_nature',
        title: 'Par type',
        description: 'Répartition par type (Installation / Dépannage) avec détail par nature',
        filterKeys: ['client', 'interventionType'],
        IconComponent: BarChart2,
      },
      {
        id: 'by_tech',
        title: 'Par technicien',
        description: 'Charge, performance et interventions assignées par tech',
        filterKeys: ['client', 'technicianName'],
        IconComponent: Users,
      },
      {
        id: 'timing',
        title: "Temps d'intervention",
        description: 'Durée réelle vs prévue par technicien et nature',
        filterKeys: ['client'],
        IconComponent: Clock,
      },
      {
        id: 'planning',
        title: 'Planning',
        description: 'Interventions planifiées et à venir',
        filterKeys: ['client', 'technicianName'],
        IconComponent: Clock,
      },
      // ── Flotte & équipement ──
      {
        id: 'maintenance',
        title: 'Maintenance',
        description: 'Règles de maintenance — catégorie, déclencheur, récurrence',
        filterKeys: [],
        IconComponent: Wrench,
      },
      {
        id: 'pneus',
        title: 'Pneus',
        description: "Suivi de l'usure par pneu et par engin — alertes remplacement",
        filterKeys: ['vehicle'],
        IconComponent: CircleDot,
      },
      {
        id: 'depenses',
        title: 'Dépenses par véhicule',
        description: 'Coûts par engin : carburant, réparation, péage, assurance, etc.',
        filterKeys: ['vehicle', 'client'],
        IconComponent: Receipt,
      },
      {
        id: 'temperature',
        title: 'Températures & Batterie',
        description: 'Surveillance thermique moteur et tension batterie par engin',
        filterKeys: ['vehicle', 'client'],
        IconComponent: Thermometer,
      },
      {
        id: 'capteurs',
        title: 'Capteurs & Télémétrie',
        description: 'Ignition, batterie, sonde carburant — état par engin',
        filterKeys: ['vehicle', 'client'],
        IconComponent: Gauge,
      },
      // ── Géographie & règles ──
      {
        id: 'geofencing',
        title: 'Géofencing',
        description: 'Zones de surveillance — type, statut et couverture',
        filterKeys: [],
        IconComponent: MapPin,
      },
      {
        id: 'poi',
        title: "Points d'intérêt (POI)",
        description: 'Liste des POI configurés — type et coordonnées',
        filterKeys: [],
        IconComponent: Navigation,
      },
      {
        id: 'eco_driving',
        title: 'Éco-conduite',
        description: 'Profils éco-conduite — scores cibles, vitesse max, sensibilités',
        filterKeys: [],
        IconComponent: Leaf,
      },
      // ── Monitoring ──
      {
        id: 'stock',
        title: 'Stock',
        description: 'État du stock matériel — niveaux critiques et valorisation',
        filterKeys: [],
        IconComponent: Package,
      },
      {
        id: 'monitoring',
        title: 'Monitoring balises',
        description: 'État des balises GPS — signal, connexions, anomalies',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Database,
      },
      {
        id: 'signal',
        title: 'Qualité signal',
        description: 'Taux de couverture et qualité par balise',
        filterKeys: ['client', 'revendeur'],
        IconComponent: TrendingUp,
      },
      {
        id: 'telecom_anomalies',
        title: 'Anomalies télématiques',
        description: 'Balises avec données incohérentes ou absentes',
        filterKeys: ['client', 'revendeur'],
        IconComponent: AlertTriangle,
      },
      {
        id: 'immobilisation',
        title: 'Immobilisations',
        description: 'Historique des immobilisations et remises en marche par engin',
        filterKeys: ['vehicle', 'client'],
        IconComponent: Lock,
      },
    ],
  },

  // ── 8. SUPPORT ─────────────────────────────────────────────────────────────
  {
    id: 'support',
    title: 'Support',
    subtitle: 'Tickets, SLA, agents et anomalies',
    IconComponent: LifeBuoy,
    color: '#F97316',
    roles: SUPPORT_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs support : tickets, SLA, délais, satisfaction',
        filterKeys: ['client'],
        IconComponent: BarChart2,
      },
      {
        id: 'all',
        title: 'Tous les tickets',
        description: 'Historique complet des tickets',
        filterKeys: ['client'],
        IconComponent: LifeBuoy,
      },
      {
        id: 'open',
        title: 'Ouverts & En cours',
        description: 'Tickets actifs nécessitant une action',
        filterKeys: ['client'],
        IconComponent: AlertTriangle,
      },
      {
        id: 'resolved',
        title: 'Résolus & Fermés',
        description: 'Tickets clôturés sur la période',
        filterKeys: ['client'],
        IconComponent: Check,
      },
      {
        id: 'by_priority',
        title: 'Par priorité',
        description: 'Répartition CRITICAL / HIGH / MEDIUM / LOW',
        filterKeys: ['client'],
        IconComponent: BarChart2,
      },
      {
        id: 'by_agent',
        title: 'Par agent',
        description: 'Charge, résolutions et délais par agent',
        filterKeys: ['client'],
        IconComponent: Users,
      },
      {
        id: 'sla',
        title: 'SLA',
        description: 'Respect des délais contractuels par priorité',
        filterKeys: ['client'],
        IconComponent: Clock,
      },
      {
        id: 'anomalies',
        title: 'Tickets en anomalie',
        description: 'Non assignés · SLA dépassé · En attente bloqué · Doublons',
        filterKeys: ['client'],
        IconComponent: AlertTriangle,
      },
    ],
  },

  // ── 9. ADMIN ───────────────────────────────────────────────────────────────
  {
    id: 'admin',
    title: 'Admin',
    subtitle: 'Supervision globale, logs, utilisateurs et revendeurs',
    IconComponent: Settings,
    color: '#6B7280',
    roles: ADMIN_ROLES,
    subReports: [
      {
        id: 'synthese',
        title: 'Synthèse',
        description: 'KPIs plateforme : engins, users, tickets, alertes, balises',
        filterKeys: ['revendeur'],
        IconComponent: BarChart2,
      },
      {
        id: 'users',
        title: 'Utilisateurs actifs',
        description: 'Comptes actifs — rôles, connexions, clients',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Users,
      },
      {
        id: 'user_activity',
        title: 'Activité utilisateurs',
        description: 'Connexions, actions et modules utilisés par user',
        filterKeys: ['client', 'revendeur'],
        IconComponent: TrendingUp,
      },
      {
        id: 'resellers',
        title: 'Activité revendeurs',
        description: 'Activité, clients et indicateurs par revendeur',
        filterKeys: ['revendeur'],
        IconComponent: BarChart2,
      },
      {
        id: 'logs',
        title: 'Logs système',
        description: 'Journal des actions — date, user, module, IP',
        filterKeys: ['client', 'revendeur'],
        IconComponent: Database,
      },
      {
        id: 'audit',
        title: 'Audit trail',
        description: "Historique des modifications d'entités critiques",
        filterKeys: ['client', 'revendeur'],
        IconComponent: Shield,
      },
    ],
  },

  // ── 10. SUPERADMIN ─────────────────────────────────────────────────────────
  {
    id: 'superadmin',
    title: 'Superadmin',
    subtitle: 'Vision globale de toute la plateforme TrackYu',
    IconComponent: Shield,
    color: '#DC2626',
    roles: [ROLE.SUPERADMIN],
    subReports: [
      {
        id: 'synthese',
        title: 'Dashboard global',
        description: 'KPIs plateforme : tenants, MRR, balises, alertes/24h',
        filterKeys: [],
        IconComponent: BarChart2,
      },
      {
        id: 'by_tenant',
        title: 'Par revendeur',
        description: 'Activité, revenus et indicateurs par tenant',
        filterKeys: ['revendeur'],
        IconComponent: Users,
      },
      {
        id: 'mrr',
        title: 'MRR / ARR',
        description: 'Revenus récurrents — évolution et croissance',
        filterKeys: ['revendeur'],
        IconComponent: TrendingUp,
      },
      {
        id: 'gps_activity',
        title: 'Activité GPS globale',
        description: 'Trames reçues, balises actives, véhicules en mouvement',
        filterKeys: ['revendeur'],
        IconComponent: Database,
      },
      {
        id: 'balises',
        title: 'Balises GPS',
        description: 'Toutes les balises — IMEI, signal, protocole, client',
        filterKeys: ['revendeur'],
        IconComponent: Database,
      },
    ],
  },
];

export default REPORT_MODULES;
